flink:
  default:
    parallelism: 2
  state:
    backend:
      type: rocksdb
      incremental: false
    checkpoints:
      dir: file:///E/GitHub/my/gmall-flink/checkpoint
      interval: 60
      concurrentCheckpoints: 1
      min:
        pause:
          between: 100
      timeout: 600
      tolerable:
        checkpoint:
          failure:
            number: 3
    checkpoint-storage: EXACTLY_ONCE
kafka:
  groupId: test3
  topics:
    consumer: ods_base_db
  consumerPath: /Users/mininglamp/Documents/workspace/gmall-flink/gmall-realtime/src/main/resources/consumer.properties
  producerPath: /Users/mininglamp/Documents/workspace/gmall-flink/gmall-realtime/src/main/resources/consumer.properties
phoenix:
  configPath: /Users/mininglamp/Documents/workspace/gmall-flink/gmall-realtime/src/main/resources/phoenix.properties
#  driver: org.apache.phoenix.jdbc.PhoenixDriver
#  url: jdbc:phoenix:192.168.106.101
mysql:
  configPath: /Users/mininglamp/Documents/workspace/gmall-flink/gmall-realtime/src/main/resources/mysql.properties
  database: realtime
  tables: realtime.table_process
  startupOption: INITIAL
jobName: ods-mysql-into-kafka
