flink:
  default:
    parallelism: 2
  state:
    backend:
      type: rocksdb
      incremental: false
    checkpoints:
      dir: file:///E/GitHub/my/gmall-flink/checkpoint
      interval: 60
      concurrentCheckpoints: 1
      min:
        pause:
          between: 100
      timeout: 600
      tolerable:
        checkpoint:
          failure:
            number: 3
    checkpoint-storage: EXACTLY_ONCE
kafka:
  topics:
    producer: ods_base_db
  producerPath: E:/GitHub/my/gmall-flink/gmall-realtime/src/main/resources/producer.properties
mysql:
  configPath: E:/GitHub/my/gmall-flink/gmall-realtime/src/main/resources/mysql.properties
  database: gmall
  startupOption: EARLIEST_OFFSET
jobName: ods-mysql-into-kafka

